name: AWS CDK Delpoy Workflow
on:
  push:
    branches: 
      - main
      - versonicasalt-patch-1
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install AWS CDK
        run: sudo npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::696860996121:role/GitHubAction-AssumeRoleWithAction
          aws-region: us-east-1

      - name: CDK Deploy
        run: cdk deploy --require-approval never